capability: fix sys/capability.h compile error
Capability testcases fail to compile with sys/capability.h of libcap-devel in
RHEL5-like distros:

In file included from /usr/include/sys/capability.h:34, from cap_bounds_r.c:30:
/usr/include/linux/capability.h:70:
         error: expected specifier-qualifier-list before '__le32'

This is due to sys/capability.h preventing the correct _LINUX_TYPES_H_ from
being included.  The problem can be bypassed by including linux/types.h in
capability testcases.

Signed-off-by: Simon Xu <xu.simon@oracle.com>
Signed-off-by: Wanlong Gao <gaowanlong@cn.fujitsu.com>