[ltp-vte] SAHARA: disable -mfpu=vfp defined in top Makefile to resolve ENGR118408
disable -mfpu=vfp defined in top Makefile, which will cause error.
Error: After calling ioctl successfully first time, it will return errno
22(EINVAL) at the second time, even not enter ioctl().